### PR TITLE
Master

### PR DESCRIPTION
**Pull request by cristian-sima**
The error is a nice human readable message

Added "between_inclusive"

The unit tests pass

### CODE REVIEW

**Comment by connor4312** [comment]
Hi, thanks for the contribution!

Better error message support would be great. I think, however, that multilingual support would be necessary. The way I'd approach implementing this would have a method on the ValidationResults which would take a "translator" interface; it then uses this convert errors and values into a human-readable form.

e.g. a quick mockup

``` go
type Translator interface {
    // takes the name of the value, and the value
    // itself, and the name(?) of the validation that failed.
    Translate(name string, value interface{}, invalid string) string
}

// Returns a map of the invalid value keys, to sentences.
func (v *ValidationResults) Translate(t Translator) map[string]string { /* ... */ }

type EnglishTranslator struct {}
// ...
```

**Comment by cristian-sima** [comment]
Hi connor4312! 

Thank you for your response. 

That is a very good idea. I will try tomorrow to integrate that and I will pull the changes.

**Comment by connor4312** [comment]
Sounds good, ping me when you have it :smile:

**Comment by cristian-sima** [comment]
I finally done the translators

I have spent some time to make sure more translators can be added and that it is using good coding practices.

**Pull request closed without merging**
